'use client'; import {useMemo,useState} from 'react'; import Link from 'next/link'; import {Plane,Bus,Train,Ship,CalendarDays,MapPin,Users,Search,ArrowRight} from 'lucide-react';
type Tab='Flights'|'Buses'|'Trains'|'Ships'|'Events'|'Parties'|'Tours';
const tabs:Tab[]=['Flights','Buses','Trains','Ships','Events','Parties','Tours'];
const flights=Array.from({length:20},(_,i)=>({id:'FL'+(100+i),from:i%2?'WIL':'NBO',to:i%3?'MBA':'KIS',operator:i%2?'Jambojet':'Kenya Airways',time:`${6+i%10}:30`,price:4500+i*350}));
const buses=Array.from({length:15},(_,i)=>({id:'RD'+(200+i),from:['Nairobi','Mombasa','Kisumu','Nakuru'][i%4],to:['Mombasa','Nairobi','Nakuru','Malindi'][i%4],operator:i%2?'ENA Coach':'Modern Coast',time:`${5+i%8}:00`,price:900+i*80}));
const trains=Array.from({length:10},(_,i)=>({id:'SGR'+(300+i),from:i%2?'Mombasa':'Nairobi',to:i%2?'Nairobi':'Mombasa',operator:'SGR Madaraka Express',time:`${7+i}:00`,price:i%3?3500:9000}));
const ships=Array.from({length:5},(_,i)=>({id:'SEA'+(400+i),from:i%2?'Likoni Mainland':'Mombasa',to:i%2?'Likoni Island':'Zanzibar',operator:i%2?'Likoni Ferry':'Ocean Cruise',time:`${9+i}:00`,price:2000+i*900}));
const generic={Events:['Nairobi Live Sessions','Sunset Afrobeat Festival','Corporate Spark Summit'],Parties:['Nairobi Neon Nights','Umoja Saturday Bash','Westlands Rooftop Party'],Tours:['Maasai Mara Day Safari','Mt Longonot Hiking Experience','Nairobi After Dark']};
const icons:any={Flights:<Plane/>,Buses:<Bus/>,Trains:<Train/>,Ships:<Ship/>,Events:<CalendarDays/>,Parties:<Users/>,Tours:<MapPin/>};
export default function Travel(){const [tab,setTab]=useState<Tab>('Flights');const [q,setQ]=useState('');const [selected,setSelected]=useState<string|null>(null);const rows=useMemo(()=>{if(tab in generic)return generic[tab as keyof typeof generic].filter(x=>x.toLowerCase().includes(q.toLowerCase())).map((x,i)=>({id:tab+i,title:x,operator:'Kenya',time:'Available',price:tab==='Tours'?6500:1500}));const data:any={Flights:flights,Buses:buses,Trains:trains,Ships:ships}[tab];return data.filter((x:any)=>(x.from+x.to+x.operator).toLowerCase().includes(q.toLowerCase()));},[tab,q]);return <main className="travelPage"><section className="pageTitle"><p className="eyebrow">APEX TRAVEL HUB</p><h1>Move. Explore. Arrive.</h1><p>Seven bookable search tabs. One unified journey.</p></section><div className="tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>{setTab(t);setSelected(null)}} key={t}>{icons[t]}{t}</button>)}</div><section className="searchPanel"><div><label>Search</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tab==='Flights'?'NBO, MBA, airline...':'Search route or experience...'}/></div><div><label>Date</label><input type="date"/></div><div><label>Passengers</label><select><option>1 passenger</option><option>2 passengers</option><option>4 passengers</option></select></div><button className="goldBtn"><Search/> Search</button></section><section className="results"><div className="resultHead"><b>{rows.length} available</b><span>Mock availability · live adapters ready</span></div>{rows.map((r:any)=><article className="result" key={r.id}><div><strong>{r.title||r.from+' → '+r.to}</strong><p>{r.operator} · {r.time}</p></div><div className="resultRight"><b>KES {Number(r.price).toLocaleString()}</b><button onClick={()=>setSelected(r.id)}>Select <ArrowRight/></button></div></article>)}</section>{selected&&<SeatPicker id={selected}/>}<Link className="itineraryLink" href="/travel/itinerary/demo">View sample combined itinerary →</Link></main>}
function SeatPicker({id}:{id:string}){const [seat,setSeat]=useState('');return <div className="modalBack"><div className="seatModal"><Link className="close" href="/travel">×</Link><p className="eyebrow">SEGMENT {id}</p><h2>Select your seat</h2><div className="seatGrid">{Array.from({length:24},(_,i)=>{const n=String.fromCharCode(65+i%6)+(Math.floor(i/6)+1);return <button disabled={i%7===0} className={seat===n?'seat chosen':'seat'} onClick={()=>setSeat(n)} key={n}>{n}</button>})}</div><div className="seatFoot"><span>{seat?'Selected '+seat:'Choose a seat'}</span><Link href="/travel/itinerary/demo" className={seat?'goldBtn':'disabledBtn'}>Continue</Link></div></div></div>}